name: Deploy to Firebase Hosting

on:
  pull_request:
    types:
      - closed
    branches:
      - Desarrollo
      - main
      
jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '18.15.0'
    - run: npm install
    
      
    -  run: npm install -g @angular/cli
    - run: ng build
    - uses: w9jds/firebase-action@master --project <selenium2-1472f>
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_LOGIN }}
