name: Deploy to Firebase Hosting

on:
  pull_request:
    types:
      - closed
    branches:
      - Desarrollo
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'  # Cambia a la versión de Node.js que necesitas

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Configure Firebase Project
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SELENIUM2_1472F }}" > service-account.json
          cat service-account.json
          npx firebase use --add epiuco  # Cambia por tu proyecto de Firebase

      - name: Build Angular app
        run: ng build --prod

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN_LOGIN}}"
